// Tests for deploy/check-catalog-state.sh — refusing to clobber the box (#146).
//
// The failure this exists to stop already happened once: a pre-render was run on
// prod, and the next deploy copied `engine/**` over it — including the committed,
// empty `catalog.json` — resetting the box to zero publishable programs. Nothing
// failed. The deploy went green.
//
// Two things were lost, and they are not equally replaceable. The manifest can be
// regenerated by re-running the pre-render (it skips combinations whose masters
// exist, so it costs minutes rather than $20 of TTS). The **approvals** cannot:
// `engine/catalog.py` requires a recorded human listen before a program is
// publishable, and no script can regenerate a person having listened.
//
// So this guard runs BEFORE the copy and fails the deploy, rather than after and
// restoring — a restore is a second thing to get right on the worst day, and by
// then the file is already gone.
//
// It runs in the CI runner over two files (what the box has, what the commit
// carries), which is what makes it testable here rather than inline in
// deploy.yml — the same reason cut-samples.sh and wait-for-idle.sh are scripts.
const { test } = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { execFile } = require('node:child_process');

const SCRIPT = path.join(__dirname, '..', 'deploy', 'check-catalog-state.sh');

function run(boxFile, repoFile, kind) {
  return new Promise((resolve) => {
    execFile('bash', [SCRIPT, boxFile, repoFile, kind], { timeout: 15000 },
      (err, stdout, stderr) => {
        resolve({ code: err ? (err.code ?? 1) : 0, out: `${stdout}${stderr}` });
      });
  });
}

let dir;
function write(name, contents) {
  dir = dir || fs.mkdtempSync(path.join(os.tmpdir(), 'catstate-'));
  const p = path.join(dir, name);
  fs.writeFileSync(p, typeof contents === 'string' ? contents : JSON.stringify(contents));
  return p;
}

/** A manifest with the given programs, as `[key, publishable]` pairs. */
const manifest = (programs) => ({
  schemaVersion: 1,
  generatedAt: '2026-09-07T12:00:00Z',
  programs: programs.map(([key, publishable]) => ({
    key, goal: key.split('__')[0], voiceSet: key.split('__')[1],
    publishable, tracks: [],
  })),
  durationsByGoal: {},
});

const approvals = (listens) => ({
  schemaVersion: 1,
  listens: listens.map(([program, at]) => ({ program, listen: 'full', at, by: 'frankbria' })),
});

const EMPTY_MANIFEST = { schemaVersion: 1, generatedAt: null, programs: [], durationsByGoal: {} };
const EMPTY_APPROVALS = { schemaVersion: 1, listens: [] };

// ---------------------------------------------------------------------------
// The catalog manifest
// ---------------------------------------------------------------------------

test('a fresh box with no manifest yet is safe to deploy over', async () => {
  // Every box is in this state until the first pre-render. Blocking here would
  // block every deploy for weeks.
  const repo = write('repo1.json', EMPTY_MANIFEST);
  const res = await run(path.join(dir, 'does-not-exist.json'), repo, 'catalog');
  assert.strictEqual(res.code, 0, res.out);
});

test('an empty box manifest is safe to deploy over', async () => {
  const box = write('box2.json', EMPTY_MANIFEST);
  const repo = write('repo2.json', EMPTY_MANIFEST);
  assert.strictEqual((await run(box, repo, 'catalog')).code, 0);
});

test('a box matching the commit is safe to deploy over', async () => {
  // The normal state once the loop is closed: the pre-render output was
  // committed back, so the two agree and the copy is a no-op.
  const programs = [['polymath__male', true], ['river__female', false]];
  const box = write('box3.json', manifest(programs));
  const repo = write('repo3.json', manifest(programs));
  assert.strictEqual((await run(box, repo, 'catalog')).code, 0);
});

test('a commit carrying MORE than the box is safe to deploy', async () => {
  // Deploying newly committed pre-render output. Strictly additive, nothing lost.
  const box = write('box4.json', manifest([['polymath__male', true]]));
  const repo = write('repo4.json',
    manifest([['polymath__male', true], ['river__female', true]]));
  assert.strictEqual((await run(box, repo, 'catalog')).code, 0);
});

test('a deploy that would erase the box manifest fails', async () => {
  // The exact incident: prod pre-rendered, the repo copy is still empty.
  const box = write('box5.json', manifest([['polymath__male', true]]));
  const repo = write('repo5.json', EMPTY_MANIFEST);
  const res = await run(box, repo, 'catalog');
  assert.strictEqual(res.code, 1, 'the deploy was allowed to erase the manifest');
  assert.match(res.out, /polymath__male/, 'the operator is not told what would be lost');
});

test('a deploy that would un-publish a program on the box fails', async () => {
  // Subtler and worse: both sides list the program, but the box's copy carries
  // the listen. Comparing counts alone would wave this through.
  const box = write('box6.json', manifest([['polymath__male', true]]));
  const repo = write('repo6.json', manifest([['polymath__male', false]]));
  const res = await run(box, repo, 'catalog');
  assert.strictEqual(res.code, 1, 'a publishable program was silently demoted');
  assert.match(res.out, /polymath__male/);
});

test('the failure says how to resolve it, not just that it failed', async () => {
  // An operator hitting this at 2am needs the next command, not a diagnosis.
  const box = write('box7.json', manifest([['polymath__male', true]]));
  const repo = write('repo7.json', EMPTY_MANIFEST);
  const res = await run(box, repo, 'catalog');
  assert.match(res.out, /commit/i,
    'the message does not say to commit the box state back');
});

// ---------------------------------------------------------------------------
// The approvals file — the half no script can regenerate
// ---------------------------------------------------------------------------

test('a listen recorded on the box and not in the commit fails the deploy', async () => {
  const box = write('box8.json', approvals([['polymath__male', '2026-09-07T10:00:00Z']]));
  const repo = write('repo8.json', EMPTY_APPROVALS);
  const res = await run(box, repo, 'approvals');
  assert.strictEqual(res.code, 1, 'a human listen was about to be deleted');
  assert.match(res.out, /polymath__male/);
});

test('the same listen spelled two legal ways is not a blocked deploy', async () => {
  // engine/catalog.py:100-103 documents exactly this: timestamps arrive as `Z`
  // when hand-typed and `+00:00` from the engine's isoformat(). Same instant,
  // same listen. Comparing the raw strings blocks a deploy that loses nothing —
  // fail-closed, so not a data loss, but a 2am block for no reason.
  const box = write('box17.json', approvals([['polymath__male', '2026-09-07T10:00:00Z']]));
  const repo = write('repo17.json', approvals([['polymath__male', '2026-09-07T10:00:00+00:00']]));
  const res = await run(box, repo, 'approvals');
  assert.strictEqual(res.code, 0, res.out);
});

test('a full listen downgraded to a spot check is not silently accepted', async () => {
  // Same program, same instant, different claim. catalog.py treats a full listen
  // and a spot check as different things — #58's criterion needs one full listen
  // across the catalog — so losing the full one can take every program with it.
  const box = write('box18.json',
    { schemaVersion: 1, listens: [{ program: 'polymath__male', listen: 'full', at: '2026-09-07T10:00:00Z' }] });
  const repo = write('repo18.json',
    { schemaVersion: 1, listens: [{ program: 'polymath__male', listen: 'spot', at: '2026-09-07T10:00:00Z' }] });
  assert.strictEqual((await run(box, repo, 'approvals')).code, 1,
    'a full listen was replaced by a spot check without complaint');
});

test('a listen with no timestamp does not report itself as "None"', async () => {
  const box = write('box19.json',
    { schemaVersion: 1, listens: [{ program: 'polymath__male', listen: 'full', at: null }] });
  const repo = write('repo19.json', EMPTY_APPROVALS);
  const res = await run(box, repo, 'approvals');
  assert.strictEqual(res.code, 1);
  assert.ok(!/None/.test(res.out), 'a null timestamp leaked Python\'s None into operator output');
});

test('approvals already in the commit deploy cleanly', async () => {
  const listens = [['polymath__male', '2026-09-07T10:00:00Z']];
  const box = write('box9.json', approvals(listens));
  const repo = write('repo9.json', approvals(listens));
  assert.strictEqual((await run(box, repo, 'approvals')).code, 0);
});

// ---------------------------------------------------------------------------
// Files that cannot be read
// ---------------------------------------------------------------------------

test('a corrupt box manifest does not block the deploy', async () => {
  // server.js already treats an unparseable manifest as no manifest, so nothing
  // on the box is serving from it — there is no state left to protect, and
  // blocking every future deploy on a broken file is the worse outcome.
  const box = write('box10.json', '{not json at all');
  const repo = write('repo10.json', EMPTY_MANIFEST);
  const res = await run(box, repo, 'catalog');
  assert.strictEqual(res.code, 0, res.out);
  assert.match(res.out, /not valid JSON|could not be read|unreadable|parse/i,
    'a corrupt file on the box passed without saying so');
});

test('a box file that exists but cannot be opened fails the deploy', async () => {
  // The pass for a corrupt file was reasoned about UNPARSEABLE json — server.js
  // treats that as no manifest, so nothing is serving from it. A permissions
  // error is a different thing wearing the same exception: the file may be
  // perfectly good and full of programs, and we simply cannot see it. Guessing
  // "empty" there loses exactly what this guard exists to protect.
  const box = write('box14.json', manifest([['polymath__male', true]]));
  const repo = write('repo14.json', EMPTY_MANIFEST);
  fs.chmodSync(box, 0o000);
  try {
    const res = await run(box, repo, 'catalog');
    assert.strictEqual(res.code, 1, 'an unreadable box file was assumed to be empty');
  } finally {
    fs.chmodSync(box, 0o644);
  }
});

test('a schema this guard does not recognise fails the deploy', async () => {
  // The quiet catastrophe. `schemaVersion` goes to 2 and `programs` is renamed;
  // both sides then read as unrecognised, the box looks empty, and the deploy
  // proceeds to replay the original incident — green, with one stdout line.
  const box = write('box15.json',
    { schemaVersion: 2, items: [{ key: 'polymath__male', publishable: true }] });
  const repo = write('repo15.json', { schemaVersion: 2, items: [] });
  const res = await run(box, repo, 'catalog');
  assert.strictEqual(res.code, 1, 'an unrecognised schema was waved through');
  assert.match(res.out, /schema/i, 'the operator is not told the schema is the problem');
});

test('a box file of the right schema but the wrong shape fails the deploy', async () => {
  const box = write('box16.json', { schemaVersion: 1, programs: { not: 'a list' } });
  const repo = write('repo16.json', EMPTY_MANIFEST);
  assert.strictEqual((await run(box, repo, 'catalog')).code, 1);
});

test('a corrupt file in the commit fails when the box has state to lose', async () => {
  // The one direction that must not be waved through: we cannot show the commit
  // preserves anything, and the box demonstrably has something.
  const box = write('box11.json', manifest([['polymath__male', true]]));
  const repo = write('repo11.json', '{ broken');
  assert.strictEqual((await run(box, repo, 'catalog')).code, 1);
});

test('an unknown kind is a failure, not a silent pass', async () => {
  // A typo in deploy.yml must not disable the guard.
  const box = write('box12.json', EMPTY_MANIFEST);
  const repo = write('repo12.json', EMPTY_MANIFEST);
  assert.strictEqual((await run(box, repo, 'catalogue')).code, 1);
});

test('a missing interpreter fails the deploy rather than passing it', async () => {
  // A guard that goes green because it could not run is worse than no guard.
  const box = write('box13.json', manifest([['polymath__male', true]]));
  const repo = write('repo13.json', EMPTY_MANIFEST);
  const res = await new Promise((resolve) => {
    execFile('bash', [SCRIPT, box, repo, 'catalog'],
      { env: { ...process.env, HYPNO_PYTHON: '/nonexistent/python3' }, timeout: 15000 },
      (err, stdout, stderr) => resolve({ code: err ? (err.code ?? 1) : 0, out: `${stdout}${stderr}` }));
  });
  assert.strictEqual(res.code, 1, 'the guard passed without being able to check');
  assert.match(res.out, /interpreter/i);
});

test('missing arguments are a failure, not a silent pass', async () => {
  const res = await new Promise((resolve) => {
    execFile('bash', [SCRIPT], { timeout: 15000 },
      (err, stdout, stderr) => resolve({ code: err ? (err.code ?? 1) : 0, out: `${stdout}${stderr}` }));
  });
  assert.strictEqual(res.code, 1, 'the guard passed with no arguments');
});

// ---------------------------------------------------------------------------
// How deploy.yml wires it — the ordering IS the guarantee
// ---------------------------------------------------------------------------

test('the guard runs before the copy that would overwrite the files', () => {
  // Textual, because the workflow is YAML rather than something runnable here.
  // This ordering is the entire mechanism: run after the copy and the check is
  // reporting on a file it has already destroyed. Reversing these two steps
  // would leave a green, useless check in place.
  const yml = fs.readFileSync(
    path.join(__dirname, '..', '.github', 'workflows', 'deploy.yml'), 'utf8');
  // Anchored on the INVOCATIONS, not on the script name: its first appearance in
  // the file is the staging step's `source:` list. Matching that would let the
  // "Refuse" step be moved after the copy with this test still green — the very
  // hole it exists to close.
  const copy = yml.indexOf('Copy app + engine to server');
  assert.ok(copy >= 0, 'deploy.yml no longer has the copy step');
  const calls = [...yml.matchAll(/bash "\$STAGED\/deploy\/check-catalog-state\.sh"/g)];
  assert.ok(calls.length > 0, 'deploy.yml no longer runs the catalog-state guard');
  for (const c of calls) {
    assert.ok(c.index < copy,
      'a guard invocation runs after the copy, so it checks a file already overwritten');
  }
});

test('the guard step aborts on the first failure', () => {
  // Without `set -e` the first guard's exit 1 is swallowed, the cleanup runs,
  // the step exits 0, and the deploy proceeds — a green check that guards
  // nothing. Load-bearing enough to pin.
  const yml = fs.readFileSync(
    path.join(__dirname, '..', '.github', 'workflows', 'deploy.yml'), 'utf8');
  const step = yml.slice(yml.indexOf('Refuse to clobber'), yml.indexOf('Copy app + engine to server'));
  assert.match(step, /set -e/,
    'the guard step does not abort on failure, so a refusal would be ignored');
});

test('the guard is not staged anywhere a co-tenant can write', () => {
  // DEPLOYMENT.md: "Shared server." A predictable path under world-writable
  // /tmp lets a co-tenant pre-create the directory and then swap the guard
  // script between the scp and the ssh step, symlink it at /srv so the staging
  // copy becomes the clobber, or chmod it so cleanup fails and every later
  // deploy dies. Under the app root only the deploy user can write.
  const yml = fs.readFileSync(
    path.join(__dirname, '..', '.github', 'workflows', 'deploy.yml'), 'utf8');
  assert.ok(!/target:\s*"\/tmp/.test(yml),
    'a deploy artefact is staged under world-writable /tmp on a shared host');
  assert.ok(!/STAGED=\/tmp/.test(yml),
    'the guard is executed from world-writable /tmp on a shared host');
  assert.match(yml, /STAGED=\/srv\/hypnosis-studio\//,
    'the staging path is no longer under the deploy user\'s own tree');
});

test('the staged copy is cleaned up even when the guard refuses', () => {
  // Without the trap, `set -e` skips the cleanup on refusal, and the next run
  // compares against a previous commit's staged files if `source:` ever changes.
  const yml = fs.readFileSync(
    path.join(__dirname, '..', '.github', 'workflows', 'deploy.yml'), 'utf8');
  const step = yml.slice(yml.indexOf('Refuse to clobber'), yml.indexOf('Copy app + engine to server'));
  assert.match(step, /trap .*rm -rf .*EXIT/,
    'the staged files are only removed on success');
});

test('the guard covers the approvals file, not just the manifest', () => {
  // The manifest can be rebuilt from masters that already exist. A recorded
  // listen cannot be rebuilt by anything, so leaving it unguarded would protect
  // the cheap half and lose the expensive one.
  const yml = fs.readFileSync(
    path.join(__dirname, '..', '.github', 'workflows', 'deploy.yml'), 'utf8');
  // Matched on the invocations themselves, not on the string appearing in the
  // file: the `source:` line and the explanatory comment both name the script
  // and the approvals file, so a looser pattern passes with the check deleted.
  // (It did. This test was written loose and the mutation walked straight
  // through it.)
  const calls = yml.match(/bash "\$STAGED\/deploy\/check-catalog-state\.sh"/g) || [];
  assert.strictEqual(calls.length, 2,
    `the guard is invoked ${calls.length} time(s); both files need checking`);
  assert.match(yml, /catalog\.json"\s+catalog\s*$/m,
    'nothing checks the manifest');
  assert.match(yml, /catalog-approvals\.json"\s+approvals\s*$/m,
    'nothing checks the approvals file, which is the half no script can regenerate');
});
