// Tests for deploy/check-catalog-state.sh — refusing to clobber the box (#146).
//
// The failure this exists to stop already happened once: a pre-render was run on
// prod, and the next deploy copied `engine/**` over it — including the committed,
// empty `catalog.json` — resetting the box to zero publishable programs. Nothing
// failed. The deploy went green.
//
// Two things were lost, and they are not equally replaceable. The manifest can be
// regenerated by re-running the pre-render (it skips combinations whose masters
// exist, so it costs minutes rather than $20 of TTS). The **approvals** cannot:
// `engine/catalog.py` requires a recorded human listen before a program is
// publishable, and no script can regenerate a person having listened.
//
// So this guard runs BEFORE the copy and fails the deploy, rather than after and
// restoring — a restore is a second thing to get right on the worst day, and by
// then the file is already gone.
//
// It runs in the CI runner over two files (what the box has, what the commit
// carries), which is what makes it testable here rather than inline in
// deploy.yml — the same reason cut-samples.sh and wait-for-idle.sh are scripts.
const { test } = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { execFile } = require('node:child_process');

const SCRIPT = path.join(__dirname, '..', 'deploy', 'check-catalog-state.sh');

function run(boxFile, repoFile, kind) {
  return new Promise((resolve) => {
    execFile('bash', [SCRIPT, boxFile, repoFile, kind], { timeout: 15000 },
      (err, stdout, stderr) => {
        resolve({ code: err ? (err.code ?? 1) : 0, out: `${stdout}${stderr}` });
      });
  });
}

let dir;
function write(name, contents) {
  dir = dir || fs.mkdtempSync(path.join(os.tmpdir(), 'catstate-'));
  const p = path.join(dir, name);
  fs.writeFileSync(p, typeof contents === 'string' ? contents : JSON.stringify(contents));
  return p;
}

/** A manifest with the given programs, as `[key, publishable]` pairs. */
const manifest = (programs) => ({
  schemaVersion: 1,
  generatedAt: '2026-09-07T12:00:00Z',
  programs: programs.map(([key, publishable]) => ({
    key, goal: key.split('__')[0], voiceSet: key.split('__')[1],
    publishable, tracks: [],
  })),
  durationsByGoal: {},
});

const approvals = (listens) => ({
  schemaVersion: 1,
  listens: listens.map(([program, at]) => ({ program, listen: 'full', at, by: 'frankbria' })),
});

const EMPTY_MANIFEST = { schemaVersion: 1, generatedAt: null, programs: [], durationsByGoal: {} };
const EMPTY_APPROVALS = { schemaVersion: 1, listens: [] };

// ---------------------------------------------------------------------------
// The catalog manifest
// ---------------------------------------------------------------------------

test('a fresh box with no manifest yet is safe to deploy over', async () => {
  // Every box is in this state until the first pre-render. Blocking here would
  // block every deploy for weeks.
  const repo = write('repo1.json', EMPTY_MANIFEST);
  const res = await run(path.join(dir, 'does-not-exist.json'), repo, 'catalog');
  assert.strictEqual(res.code, 0, res.out);
});

test('an empty box manifest is safe to deploy over', async () => {
  const box = write('box2.json', EMPTY_MANIFEST);
  const repo = write('repo2.json', EMPTY_MANIFEST);
  assert.strictEqual((await run(box, repo, 'catalog')).code, 0);
});

test('a box matching the commit is safe to deploy over', async () => {
  // The normal state once the loop is closed: the pre-render output was
  // committed back, so the two agree and the copy is a no-op.
  const programs = [['polymath__male', true], ['river__female', false]];
  const box = write('box3.json', manifest(programs));
  const repo = write('repo3.json', manifest(programs));
  assert.strictEqual((await run(box, repo, 'catalog')).code, 0);
});

test('a commit carrying MORE than the box is safe to deploy', async () => {
  // Deploying newly committed pre-render output. Strictly additive, nothing lost.
  const box = write('box4.json', manifest([['polymath__male', true]]));
  const repo = write('repo4.json',
    manifest([['polymath__male', true], ['river__female', true]]));
  assert.strictEqual((await run(box, repo, 'catalog')).code, 0);
});

test('a deploy that would erase the box manifest fails', async () => {
  // The exact incident: prod pre-rendered, the repo copy is still empty.
  const box = write('box5.json', manifest([['polymath__male', true]]));
  const repo = write('repo5.json', EMPTY_MANIFEST);
  const res = await run(box, repo, 'catalog');
  assert.strictEqual(res.code, 1, 'the deploy was allowed to erase the manifest');
  assert.match(res.out, /polymath__male/, 'the operator is not told what would be lost');
});

test('a deploy that would un-publish a program on the box fails', async () => {
  // Subtler and worse: both sides list the program, but the box's copy carries
  // the listen. Comparing counts alone would wave this through.
  const box = write('box6.json', manifest([['polymath__male', true]]));
  const repo = write('repo6.json', manifest([['polymath__male', false]]));
  const res = await run(box, repo, 'catalog');
  assert.strictEqual(res.code, 1, 'a publishable program was silently demoted');
  assert.match(res.out, /polymath__male/);
});

test('the failure says how to resolve it, not just that it failed', async () => {
  // An operator hitting this at 2am needs the next command, not a diagnosis.
  const box = write('box7.json', manifest([['polymath__male', true]]));
  const repo = write('repo7.json', EMPTY_MANIFEST);
  const res = await run(box, repo, 'catalog');
  assert.match(res.out, /commit/i,
    'the message does not say to commit the box state back');
});

// ---------------------------------------------------------------------------
// The approvals file — the half no script can regenerate
// ---------------------------------------------------------------------------

test('a listen recorded on the box and not in the commit fails the deploy', async () => {
  const box = write('box8.json', approvals([['polymath__male', '2026-09-07T10:00:00Z']]));
  const repo = write('repo8.json', EMPTY_APPROVALS);
  const res = await run(box, repo, 'approvals');
  assert.strictEqual(res.code, 1, 'a human listen was about to be deleted');
  assert.match(res.out, /polymath__male/);
});

test('approvals already in the commit deploy cleanly', async () => {
  const listens = [['polymath__male', '2026-09-07T10:00:00Z']];
  const box = write('box9.json', approvals(listens));
  const repo = write('repo9.json', approvals(listens));
  assert.strictEqual((await run(box, repo, 'approvals')).code, 0);
});

// ---------------------------------------------------------------------------
// Files that cannot be read
// ---------------------------------------------------------------------------

test('a corrupt box manifest does not block the deploy', async () => {
  // server.js already treats an unparseable manifest as no manifest, so nothing
  // on the box is serving from it — there is no state left to protect, and
  // blocking every future deploy on a broken file is the worse outcome.
  const box = write('box10.json', '{not json at all');
  const repo = write('repo10.json', EMPTY_MANIFEST);
  const res = await run(box, repo, 'catalog');
  assert.strictEqual(res.code, 0, res.out);
  assert.match(res.out, /could not be read|unreadable|parse/i,
    'a corrupt file on the box passed without saying so');
});

test('a corrupt file in the commit fails when the box has state to lose', async () => {
  // The one direction that must not be waved through: we cannot show the commit
  // preserves anything, and the box demonstrably has something.
  const box = write('box11.json', manifest([['polymath__male', true]]));
  const repo = write('repo11.json', '{ broken');
  assert.strictEqual((await run(box, repo, 'catalog')).code, 1);
});

test('an unknown kind is a failure, not a silent pass', async () => {
  // A typo in deploy.yml must not disable the guard.
  const box = write('box12.json', EMPTY_MANIFEST);
  const repo = write('repo12.json', EMPTY_MANIFEST);
  assert.strictEqual((await run(box, repo, 'catalogue')).code, 1);
});

test('a missing interpreter fails the deploy rather than passing it', async () => {
  // A guard that goes green because it could not run is worse than no guard.
  const box = write('box13.json', manifest([['polymath__male', true]]));
  const repo = write('repo13.json', EMPTY_MANIFEST);
  const res = await new Promise((resolve) => {
    execFile('bash', [SCRIPT, box, repo, 'catalog'],
      { env: { ...process.env, HYPNO_PYTHON: '/nonexistent/python3' }, timeout: 15000 },
      (err, stdout, stderr) => resolve({ code: err ? (err.code ?? 1) : 0, out: `${stdout}${stderr}` }));
  });
  assert.strictEqual(res.code, 1, 'the guard passed without being able to check');
  assert.match(res.out, /interpreter/i);
});

test('missing arguments are a failure, not a silent pass', async () => {
  const res = await new Promise((resolve) => {
    execFile('bash', [SCRIPT], { timeout: 15000 },
      (err, stdout, stderr) => resolve({ code: err ? (err.code ?? 1) : 0, out: `${stdout}${stderr}` }));
  });
  assert.strictEqual(res.code, 1, 'the guard passed with no arguments');
});

// ---------------------------------------------------------------------------
// How deploy.yml wires it — the ordering IS the guarantee
// ---------------------------------------------------------------------------

test('the guard runs before the copy that would overwrite the files', () => {
  // Textual, because the workflow is YAML rather than something runnable here.
  // This ordering is the entire mechanism: run after the copy and the check is
  // reporting on a file it has already destroyed. Reversing these two steps
  // would leave a green, useless check in place.
  const yml = fs.readFileSync(
    path.join(__dirname, '..', '.github', 'workflows', 'deploy.yml'), 'utf8');
  const guard = yml.indexOf('check-catalog-state.sh');
  const copy = yml.indexOf('Copy app + engine to server');
  assert.ok(guard >= 0, 'deploy.yml no longer runs the catalog-state guard');
  assert.ok(copy >= 0, 'deploy.yml no longer has the copy step');
  assert.ok(guard < copy,
    'the guard runs after the copy, so it checks a file already overwritten');
});

test('the guard covers the approvals file, not just the manifest', () => {
  // The manifest can be rebuilt from masters that already exist. A recorded
  // listen cannot be rebuilt by anything, so leaving it unguarded would protect
  // the cheap half and lose the expensive one.
  const yml = fs.readFileSync(
    path.join(__dirname, '..', '.github', 'workflows', 'deploy.yml'), 'utf8');
  // Matched on the invocations themselves, not on the string appearing in the
  // file: the `source:` line and the explanatory comment both name the script
  // and the approvals file, so a looser pattern passes with the check deleted.
  // (It did. This test was written loose and the mutation walked straight
  // through it.)
  const calls = yml.match(/bash "\$STAGED\/deploy\/check-catalog-state\.sh"/g) || [];
  assert.strictEqual(calls.length, 2,
    `the guard is invoked ${calls.length} time(s); both files need checking`);
  assert.match(yml, /catalog\.json"\s+catalog\s*$/m,
    'nothing checks the manifest');
  assert.match(yml, /catalog-approvals\.json"\s+approvals\s*$/m,
    'nothing checks the approvals file, which is the half no script can regenerate');
});
